//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLServer_MagazinFructe_CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Products
    {
        public int productID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
    }
}
